parameters:
  dockerHubUsername: ''
  imageName: ''
  containerRegistry: ''
  dockerfilePath: ''
  imageTag: ''

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: New-agent
    steps:
    - task: Docker@2
      displayName: Build Docker Image
      inputs:
        command: build
        dockerfile: ${{ parameters.dockerfilePath }}
        repository: '${{ parameters.dockerHubUsername }}/${{ parameters.imageName }}'
        tags: |
          ${{ parameters.imageTag }}

- stage: Push
  displayName: Push image
  dependsOn: Build
  jobs:
  - job: Push
    displayName: Push
    pool:
      name: New-agent
    steps:
    - task: Docker@2
      displayName: Push Docker Image
      inputs:
        containerRegistry: ${{ parameters.containerRegistry }}
        repository: '${{ parameters.dockerHubUsername }}/${{ parameters.imageName }}'
        command: push
        tags: |
          ${{ parameters.imageTag }}
